
--INSERT INTO T_CATEGORY (CATEGORY)
--VALUES ('Home'), ('Transportation'), ('Food');


--INSERT INTO T_SUB_CATEGORY (SUB_CATEGORY, CATEGORY_ID)
--VALUES ('Electricity', (SELECT ID FROM T_CATEGORY WHERE CATEGORY = 'Home')),
--       ('Groceries', (SELECT ID FROM T_CATEGORY WHERE CATEGORY = 'Home'));

--INSERT INTO T_SUB_CATEGORY (SUB_CATEGORY, CATEGORY_ID)
--SELECT ('Electricity', ID), ('Groceries', ID)
--FROM T_CATEGORY
--WHERE CATEGORY = 'Home';

--CREATE TABLE T_CATEGORY
--(ID UUID DEFAULT uuid() PRIMARY KEY,
--CATEGORY VARCHAR(20));

--CREATE TABLE T_SUB_CATEGORY
--(ID UUID DEFAULT uuid() PRIMARY KEY,
--SUB_CATEGORY VARCHAR(20));

INSERT INTO T_USER (ID, EMAIL) VALUES ('6b246024-59b1-4716-b583-9a0c4d0e519b', 'admin@admin.admin');
--CREATE TABLE T_USER (ID uuid DEFAULT uuid() PRIMARY KEY, EMAIL varchar(50) UNIQUE, PASSWORD varchar(20) NOT NULL);

INSERT INTO T_WALLET (ID, DATE_CREATED, AMOUNT, OWNER_ID) VALUES ('6b246024-59b1-4716-b583-9a0c4d0e509b', 1735313536173, 45, '6b246024-59b1-4716-b583-9a0c4d0e519b');
--CREATE TABLE T_WALLET (ID UUID DEFAULT uuid() PRIMARY KEY, DATE_CREATED BIGINT NOT NULL, AMOUNT INT DEFAULT 0, OWNER_ID UUID, FOREIGN KEY(OWNER_ID) REFERENCES T_USER(ID));
